#!/usr/bin/env bash

updates_aur="$(cat /tmp/upgrades)"

[ "${updates_aur}" == "" ] && paru -Qum 2> /dev/null | wc -l > /tmp/upgrades

updates_aur=$(cat /tmp/upgrades)

text="$updates_aur package updates available"

printf "$text" 
echo ""
echo ""
